### ISSUE TITLE
<accordion> UI

### ISSUE THREAD

**Issue by anthyeung** [ComboStrap/dokuwiki-template-strap#2]
First of all, congratulations and thank you for making such an impressive Dokuwiki theme! It has many great features (especially with improved rendering performance and SEO), and I am surprised more people have not been using this theme.

One question I had is if you will be planning to implement the <accordion> UI:
https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example

Thanks!

**Comment by gerardnico** [comment]
Thanks for the good words. You are the first to ask it. We will add it.

Cheers
Nico

**Comment by gerardnico** [comment]
Something like that ?
https://combostrap.com/ui/accordion

**Comment by anthyeung** [comment]
Yes, exactly what I was looking for! That was a fast implementation!

**Comment by gerardnico** [comment]
Thanks for the feedback !
This is not yet released. I reopen and will close it when releasing.

**Comment by gerardnico** [comment]
The new version has been released.
https://combostrap.com/changes#version_112_-_2021-03-19

The new release is tested actually on key clients for a couple of days.
You can test it or wait that I publish the date on dokuwiki (The build has passed)

Nice weekend
