### ISSUE TITLE
A wikilink inside a button requires clicking in the text

### ISSUE THREAD

**Issue by atnbueno** [ComboStrap/dokuwiki-template-strap#4]
This code:
```
<btn class="col-12">[[gohere|Click Me!]]</btn> 
```
requires the user to click in the text. A click in the non-text part of the button does nothing.

I will probably fix it in my server via JavaScript, but maybe it should be fixed here.

**Comment by gerardnico** [comment]
This is also not xhtml compliant ;) 
This is to be compatible with the move plugin that the button wraps the link. 

The callstack needs to be changed to support the styling of the link as a button.

If you have some dokuwiki knowledge, the button code is located at:

https://github.com/ComboStrap/combo/blob/007225e5fb2d3f64edaccd3bd447ca26effb9d68/syntax/button.php

**Comment by gerardnico** [comment]
I spend the last two days on that. I hope you will be happy.

The button with links are now rendered as link:

https://combostrap.com/ui/button

Is this what you wanted ?

**Comment by gerardnico** [comment]
Just noticed, the ''urlextern'' dokwuiki class brings styling rules that are killing again the styling.
https://combostrap.com/ui/button#external_link_and_secondary_type

Do you use it ? Is it an idea to set another class name in case someone want to style the type of link (ie external vs internal) ?

**Comment by atnbueno** [comment]
Thank you very much for the fix. 

Too bad about the external links. Fortunately I don't need them as buttons (_he says, two days before he'll need them_ 😂).

Perhaps are you refering to the world icon external links show? Can't those extra styling rules be overriden?

**Comment by gerardnico** [comment]
With CSS, you can :) Yes, the world icon. 

Dokuwiki uses an interwiki feature to style them.
I didn't wanted to lost this feature but unfortunately, there is a class conflict.
I'm going to rest a little bit on that.

Goo evening (if any)

**Comment by gerardnico** [comment]
The new version has been released.
https://combostrap.com/changes#version_112_-_2021-03-19

The new release is tested actually on key clients for a couple of days.
You can test it or wait that I publish the date on dokuwiki (The build has passed)
