### ISSUE TITLE
Adding a link to the headerbar renders the whole page white

### ISSUE THREAD

**Issue by FUTC-Coding** [ComboStrap/dokuwiki-template-strap#6]
This is my headerbar code in :headerbar 
```
<navbar theme="dark" background-color="dark" breakpoint="xs">
<brand title="ComboStrap Home">
ComboStrap
</brand>
<collapse>
<group expand="true">
<dropdown name="ComboStrap Components">
</dropdown>
</group>
</collapse>
</navbar>
```
And this renders fine. Though as soon as I add a link between the dropdown tags and reload the page, my whole site just renders completely white and nothing more. My headerbar code looks like this, there is just the one link added but that seems to cause the issue.

```
<navbar theme="dark" background-color="dark" breakpoint="xs">
<brand title="ComboStrap Home">
ComboStrap
</brand>
<collapse>
<group expand="true">
<dropdown name="ComboStrap Components">
[[wiki:dokuwiki|DokuWiki]]
</dropdown>
</group>
</collapse>
</navbar>
```

Any Idea on how to fix this? It is my first time using dokuwiki so there is a realistic chance that it is a configuration error on my end.

**Comment by gerardnico** [comment]
Sorry for this.

Can you try to purge the cache by adding this query?
```
?purge=true
```
ie
```
https://myinstallation.com/mypage?purge=true
```
You can also do it in your page by adding before the navbar:
```
~~NOCACHE~~
```

Other questions:
- Does the request return an error ?
- What's the HTML that you get

**Comment by FUTC-Coding** [comment]
Sadly purge didnt fix the problem. There is no http error, there is html being rendered it is just empty. The html I get has an empty body
```
<body role="document" class="dokuwiki" style="padding-top: 0px;">



<!--header node-->
<!--transition: all .2s ease-->
<!--position: absolute;-->
<!--top: 0;-->
<!--left: 0;-->
<!--width: 100%;-->

</body>
```

All `meta` and `link` tags in `<head>` seem fine just the body is completely empty apart from the 6 comments inside.

**Comment by gerardnico** [comment]
If this is the only tag that you get, you have a problem with the header code for sure.

I have used your code here and you can see that it's working:

https://demo.combostrap.com/headerbar?do=source

The next step should be to check your web server log. 

We support from php 5.6.

This happens only when you add a link in the dropdown ?

**Comment by gerardnico** [comment]
Can you check if you have SimpleXml on your installation

https://combostrap.com/support/simplexml

**Comment by gerardnico** [comment]
The last version does not use simplexml to modify the style created by dokuwiki. 
https://combostrap.com/changes#version_112_-_2021-03-19

If the problem still persist, don't hesitate to open this ticket.
